### ISSUE TITLE
Mint Update Manager icon is not correct

### ISSUE THREAD

**Issue by Ikazine** [alecive/FlatWoken#113]
![2ca1f](https://cloud.githubusercontent.com/assets/23224476/25301325/6c928942-26e9-11e7-9ce8-f2a7aebedcc4.png)
The icon for the Update Manager for Linux Mint is not correct. It should be a checkmark, however, it is just a black box with rounded corners.

**Comment by alecive** [comment]
Very strange that it is black. CAn you retrieve its name in the original icon set?

**Comment by Ikazine** [comment]
From what I can tell, the mintupdate icons should be:
```
status/mintupdate-checking.png
status/mintupdate-error.png
status/mintupdate-installing.png
status/mintupdate-type-backport.png
status/mintupdate-type-kernel.png
status/mintupdate-type-package.png
status/mintupdate-type-security.png
status/mintupdate-type-unstable.png
status/mintupdate-up-to-date.png
status/mintupdate-updates-available.png
```
These paths do not exist in FlatWoken, or from what I can tell from looking in the directory.
This would also explain why the other mintupdate icons are not displayed properly.
![d0c8d](https://cloud.githubusercontent.com/assets/23224476/25318688/aa16430a-2859-11e7-8a68-aa4587175770.png)
Thank you for your work on this icon pack, by the way.

**Comment by Ikazine** [comment]
I made a mistake. I didn't have the latest version of the icon pack installed. The checkmark is fixed in the latest version. However, the rest of the mintupdate icons are broken and messed up. Refer to my screenshot below.
![f1efd](https://cloud.githubusercontent.com/assets/23224476/25352410/8a540492-28f1-11e7-982d-314830e61c09.png)

**Comment by alecive** [comment]
@Ikazine OK I should have fixed the issue. Please download the latest version of the iconset and tell me if everything looks fine to you!

**Comment by Ikazine** [comment]
The problem appears to have been fixed. Thank you.
