### ISSUE TITLE
Volume icon is upsized in gnome shell

### ISSUE THREAD

**Issue by aiphee** [alecive/FlatWoken#114]
Hi, the volume icon in Gnome shell is tiny, could it be enlarged? 

![snimek z 2017-05-03 13-17-19](https://cloud.githubusercontent.com/assets/6242394/25658410/fe95a870-3002-11e7-8ddb-825d4e724912.png)

**Comment by alecive** [comment]
Can you show me a bigger screenshot? I don't use Gnome shell and it's difficult to me to understand what you are showing me without a bigger screenshot.

Overall, what do you mean exactly? It seems big to me! Do you mean with a better resolution (ie better "defined")?

**Comment by aiphee** [comment]
It is in middle of the screen in gnome shell, yea i meant better resolution. Thanks for looking onto that.

![snimek z 2017-05-04 09-49-33](https://cloud.githubusercontent.com/assets/6242394/25694425/e93b9988-30ae-11e7-9f25-8536fd5f3dd6.png)

**Comment by alecive** [comment]
This is strange. All my icons are in SVG, which means that they can be used at any size without losing resolution. I believe that in this case is gnome shell that is having some bug, in that it does not scale up the icon at the proper resolution but it just magnifies it.

EDIT: I looked online, and I found this bug on launchpad, which confirms my assumptions. https://bugs.launchpad.net/ubuntu/+source/light-themes/+bug/964948
I'll close this as it is a gnome-shell bug, feel free to reopen it if you need further help.

**Comment by alecive** [comment]
See also https://github.com/snwh/moka-icon-theme/issues/172 https://github.com/snwh/moka-icon-theme/issues/151 https://bugs.launchpad.net/ubuntu/+source/ubuntu-mono/+bug/878439
