### ISSUE TITLE
dropbox update for icons

### ISSUE THREAD

**Issue by jenmueller** [alecive/FlatWoken#117]
Hi @alecive, 
I'd like to ask you if you were able to re upload your AwOken icons from your dropbox in deviantart as it seems that both your dropbox and mega.co.nz files are deleted. 
Thank you very much for these beautiful icons.

**Comment by alecive** [comment]
Hi @jenmueller , thanks for notifying me on this! I am not really active on DeviantArt any more, so I wasn't aware of that. I wasn't even aware that people were still using the AwOken icon set!!

Btw, I should have updated the links to my dropbox download. Closing the issue for now, feel free to reopen if you have any other issue!
