### ISSUE TITLE
Krusader icon request

### ISSUE THREAD

**Issue by SanskritFritz** [alecive/FlatWoken#118]
Hi. Could you please include Krusader into the set?

![Krusader icon](https://upload.wikimedia.org/wikipedia/commons/7/7f/User-krusader.svg)

I suppose there is not much to change here 😄

**Comment by alecive** [comment]
Hey @SanskritFritz , I am not actively developing this iconset any more (apart from some low-priority maintenance). But the icon seems a pretty easy one to do, so I would be inclined to add it!

Two questions:
 * The icon file name in the `.desktop` file of the Krusader app says that the name should be `krusader_user`, do you confirm that?
 * From the source file, I also see that there is a krusader_root icon. Is that icon used ? If it covers only a minor case, I would rather prefer not wasting everybody's time with a minor addition.

**Comment by SanskritFritz** [comment]
Hi there. In the light of only doing low priority maintenance you are diving right into my request 😃 
Thanks for your kindness, I love your icon set.
My answers to your questions: 
* Yes I can confirm, the file name is `krusader_user` which stands for "user mode" krusader.
* Yes, the red icon is used too, it is for "root mode" krusader (it is a file manager). I just didn't dare to request that too, as I already know you are short on time on this project.

**Comment by alecive** [comment]
I should have fixed the issue with https://github.com/alecive/FlatWoken/commit/aa7b4a4b9d63a96afab44cecbf89e1795a79504d . @SanskritFritz please let me know if it works on your machine(s)!

**Comment by SanskritFritz** [comment]
I can confirm it, works great.
Beautiful Krusader icons, lovely, thank you!

**Comment by alecive** [comment]
Great that it works, and that you like them!
