### ISSUE TITLE
Massive slowness since librsvg 2.41.x

### ISSUE THREAD

**Issue by felipec** [alecive/FlatWoken#119]
This is not really a bug in FlatWoken, I'm just putting this here so others don't spend a lot of time chasing the problem like I did.

It appears librsvg is being rewritten to Rust, and in the process there's massive slowness and unintended changes in behavior. For some reason FlatWoken makes things much slower in my system.

The developers don't seem particularly interested in the [regressions](https://gitlab.gnome.org/GNOME/librsvg/issues/188) they caused by such rewrite.

**Comment by alecive** [comment]
@felipec thank you for the information. This is interesting... another great example of the beauty of working with open source! I'll close it for now, since there is no fix for this.
