### ISSUE TITLE
XFCE Compatibility

### ISSUE THREAD

**Issue by alecive** [alecive/FlatWoken#28]
Thanks to Charlie Henson's help:
Linux Mint 16 XFCE - Missing or untouched Icons.
1. ~~Accessibility~~
2. Backup Tool
3. Banshee
4. Bluetooth Manager
5. ~~Bulk Rename~~
6. ~~Calibre~~
7. CMPlayer
8. ~~Character Map~~
9. Devede
10. ~~Dictionary~~
11. ~~Document Viewer~~
12. Domain Blocker
13. Driver Manager
14. ~~Calibre Extentions (E-Book Viewer) (Edit E-Book) (LRF Viewer)~~
15. ~~Fotoxx~~
16. ~~Input Method~~
17. XFCE Panel
18. New Login
19. ~~Pinta~~
20. ~~Power Manager~~
21. ~~Printers~~
22. ~~Session Startup~~
23. Software Manager
24. Software Sources
25. ~~Thunar Logo~~
26. Upload Manager
27. Window Manager
28. Window Manager Tweaks
29. ~~Xfburn﻿~~

**Comment by felipec** [comment]
Unfortunately the 22x22 icons affect the menu too. Many icons are not visible (white on light gray). So for the moment I removed the 22x22 folder and it seems to work fine.

A better solution would nice though.

**Comment by alecive** [comment]
As I said before, with the `configure` script you can make the icons dark.

**Comment by felipec** [comment]
I don't want the icons dark. Why would I want dark menu icons?

**Comment by alecive** [comment]
How do you want your icons? You can have any color you'd like. If the menu is light gray, I would have them dark.

**Comment by felipec** [comment]
Full color, of course. Why would I want anything other than this?

![Uploading menu-good.png…]()

**Comment by cibersheep** [comment]
I always used white icons <3
![imatge](https://cloud.githubusercontent.com/assets/6640041/24510692/3a5e10bc-156a-11e7-9d7a-e51ed7e7c624.png)

**Comment by alecive** [comment]
This last picture shows Awoken , not Flatwoken.
But I got your point. Yes, the only way to have full color icons if you don't like monochrome design is to remove the 22x22 folder :+1:

**Comment by felipec** [comment]
This has nothing to do with my preferences, this is the way Xfce menus work: they are full color.

This is what happens with the 22x22 folder:

![menu-bad](https://cloud.githubusercontent.com/assets/8358/24511773/e8a3b438-1529-11e7-9410-db66395a2cfc.png)

As you can see it's totally inconsistent: all the menus like "Multimedia" have full colored icons, so does the "PulseAudio Volume Control" app, but Spotify does not.

I think it's safe to say that the theme doesn't work correctly in Xfce.

Also look at the battery plugin on the lower right. With the 22x22 it has a proper icon, but not when I remove the folder.

So removing the folder isn't ideal either.

**Comment by alecive** [comment]
Inconsistency is on the eyes of the beholder (just kidding :sunglasses: )
XFCE does a pretty bad choice in not using monochrome icons for their menus, and I (as probably 95% of the UX designers out there) am strongly against this. But this is a discussion that is out of the scope of this issue.

Regarding inconsistency: unfortunately, it is a big mess. GTK/GNOME libraries a highly inconsistent in their API, plus multiple apps use multiple toolkits and this adds fragmentation. The best an icon designer can do is to provide a consistent, coherent, theme that is compliant to freedesktop standards, and then all the mess a DE/app/WM/whatever does is not his fault :grin: 
The issue is so big that I stopped doing development of icon themes / gtk themes at all. It was too frustrating to spend time in doing meaningful design with all these guys messing around.

**Comment by felipec** [comment]
Well, regardless of what Xfce chose, the menus are inconsistent as they are. I think that's objectively true.

Maybe Xfce made a bad choice, but I wouldn't accept the claim that 95% of UI designers agree with that. I personally never have seen monochrome icons for menus.

And yeah, I've dealt with GNOME/Freedesktop people, I can see why there might not be a way forward in terms of a generic solution.

Yet there must be a way of organizing the icons that works well for Xfce.

**Comment by alecive** [comment]
> Maybe Xfce made a bad choice, but I wouldn't accept the claim that 95% of UI designers agree with that. I personally never have seen monochrome icons for menus.

I think that's a thing (e.g. gnome uses monochrome icons for menus https://www.gnome.org/wp-content/uploads/2017/03/night-light.png ). In general, icons for menus are very rarely used at all nowadays, but that is out of the scope of this conversation. 
Importantly, with "menu" I mean the thing you get with a right click on the file manager, or by clicking the menu bar on top of each app. Menu icons should be small, easy to detect at a glance, contrasted with the background (this is why many people use monochrome icons).

Menu icons fundamentally differ from launchers that launch applications, like e.g. Unity, or the gnome launcher (or the macOS launcher). I agree with you that a launcher should have only colored icons. Launcher icons should be big, detailed representation of the logo/app.

To this end, what I do (and icon designers do with varying degrees of complexity) is to create a big, rich, colored version of the iconset at high resolution ( I use 512x512), and a simpler, eventually monochrome version at small resolution for menus ( I use 22x22, which is pretty standard). And this works pretty well for modern DEs that differentiate between launchers and menus like Unity and Gnome.

The main problem here is that the menu on the bottom left of your screen is actually a launcher, but for that specific launcher the UI metaphor is that of a menu (which, although it would have made sense in 2005, is wrong in 2017). Items are small, you should not have a big amount of detail for such small icons---this is where 95% of designers agree.

In this case, it's easy to have inconsistency because for icons with monochrome versions, the theme chooses them. For icons that do not have monochrome versions (because it's not necessary and I didn't do it), the bigger icon is used. This is what makes your claim below true, but not my fault: 

> Well, regardless of what Xfce chose, the menus are inconsistent as they are. I think that's objectively true.

It's objectively true that XFCE should move on and implementing a better UI metaphor for the launcher :)

And this is only one problem. Some apps/applets may do an even worse job, e.g. the session icon in the traybar: in that case, instead of asking for a generic "session" icon, the app asks for a "session" at a resolution bigger to the one it was intended (this is why it is not monochrome).

The battery applet does the right job instead. Unfortunately, here the problem is that the battery status icon is only at 22x22 resolution, because there's no reason for me to spend hundred hours designing bigger resolution versions of an icon if that icon is used only in 22x22 sizes. So if you remove the folder, there's no icon any more.

I hope that helps in explaining my position!
