### ISSUE TITLE
Redshift Icon name incorrect...

### ISSUE THREAD

**Issue by moulei** [alecive/FlatWoken#92]
Hi,

In FlatWoken & AwOken you have the names incorrect for Redshift. 

The correct names are;
```
redshift-status-on
redshift-status-off
```

On= a red color
Off= a grey color

Keep up the great work!

**Comment by alecive** [comment]
Thanks @moulei  for reporting this. It should have been fixed on commit a6c6fe25e43c563d813656a5748972933e7b0e3c , does it work for you?

**Comment by moulei** [comment]
Hi,

I'll give it a try, but I hope you can really figure out what's going on in #94

thanks
