### ISSUE TITLE
Kile icon missing

### ISSUE THREAD

**Issue by jeljaik** [alecive/FlatWoken#96]
:bow: Please?!

**Comment by alecive** [comment]
And there you have it! :)

**Comment by jeljaik** [comment]
:*

--


*Jorhabib Eljaik Gómez,**Ph.D. Student - *Istituto Italiano di Tecnologia
Dept. of Robotics, Brain and Cognitive Sciences
Cognitive Humanoids Laboratory
e-mail: jorhabib.eljaik@iit.it
Cel: +39 388 352 33 85
Tel: +39 010 71781 420
Fax: +39 010 7170817

On Sat, Mar 7, 2015 at 1:12 PM, Alessandro Roncone <notifications@github.com
