### ISSUE TITLE
Preferences Icons in Evolution (Novell) are way too large, edit Contacts Field also

### ISSUE THREAD

**Issue by kione** [alecive/FlatWoken#99]
I see a scaling issue in Novell Evolution Mail etc. Client (several Linux Distros). The SVG Icons in the Preference Dialog are scaling endless. Also while editing contacts in Evolution, the Default Icon for a Conatcts-Image is oversized. 

Definitely the Icons of my flavour, so pls hurry :) thanks for now!!
![workspace_1_010](https://cloud.githubusercontent.com/assets/12138578/7350577/476cb608-ed00-11e4-803b-09cc93892b76.png)

The small Icons inside the Client for Mail|Contacts|Calendar|Notes|Memos have also a little issue: Notes|Memo are the same...
![selection_012](https://cloud.githubusercontent.com/assets/12138578/7350678/e88d5c36-ed00-11e4-8e31-f12a602bd46e.png)

**Comment by alecive** [comment]
Has it been fixed from their side?
I tried working out a solution for that but I never found one.
